const Site=(()=>{let e=0,t=()=>{a(),document.addEventListener("DOMContentLoaded",async()=>{await l(),n()})},l=async()=>{let t=document.querySelectorAll(".roles__item");if(0===t.length)return;let l=0;t.forEach((t,a)=>{l+=.25,t.style.animationDelay=`${l}s`,e=l+.25});let a=document.querySelectorAll(".roles__border").length,n=a,s=document.getElementById("roles__text"),i=document.getElementById("roles__logo"),r=document.getElementById("roles");await new Promise(t=>setTimeout(t,1e3*e+.25)),s.classList.add("animate__fadeOut"),await new Promise(t=>setTimeout(t,500*e)),s.classList.add("d-none"),i.classList.remove("d-none"),i.classList.add("animate__fadeInDown","animate__animated"),await new Promise(e=>setTimeout(e,500*n)),await new Promise(e=>setTimeout(e,1e3)),i.classList.add("animate__fadeOutUp"),r.classList.add("d-none");let o=document.getElementById("body");if(o.classList.remove("overflow-hidden"),"loading"in HTMLIFrameElement.prototype){let c=document.querySelectorAll('iframe[loading="lazy"]');c.forEach(e=>{e.src=e.dataset.src})}let d=document.querySelectorAll('img[loading="lazy"]');d.forEach(e=>{e.src=e.dataset.src})},a=()=>{let e=document.getElementById("power-switch");e.addEventListener("click",function(){e.classList.toggle("power-off"),e.classList.toggle("power-on");let t=document.querySelectorAll(".page");t.forEach((e,t)=>{e.classList.toggle("light")})})},n=()=>{let e=document.getElementById("brands");fetch("brands.json").then(e=>e.json()).then(t=>{let l=`
          ${t.map(e=>`
            <li class="brand">
              <img loading="lazy" src="images/${e.src}" width="${e.width}"  height="${e.width}" alt="${e.alt}" />
            </li>
          `).join("")}
        `;e.innerHTML=l}).catch(t=>{console.log(t);let l=`
            <li class="brand text-center">
              Las marcas no fueron cargadas
            </li>
        `;e.innerHTML=l})},s=(e,t)=>{e.preventDefault();var l,t=document.getElementById(t),a=window.scrollY,n=t.getBoundingClientRect().top-a;function s(e){var t=Math.min(e/500,1);window.scroll(0,a+n*t),t<1&&requestAnimationFrame(s)}requestAnimationFrame(s)},i=(e,t)=>{e.preventDefault(),t.querySelectorAll(".fa-solid")[0].classList.toggle("active");let l=t.closest(".parent"),a=l.querySelectorAll(".read-more");a.forEach((e,t)=>{e.classList.toggle("active")})};return{init:t,animateScroll:s,readMore:i}})();Site.init();